ooone mooore tiiime

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -116,8 +116,17 @@ jobs:
             - node_modules
       - run: *build
       - run: *test
-      - run: *verify-test-artifacts
+      - run:
+          name: Verify test artifacts
           shell: bash.exe
+          command: |
+            TEST_ARTIFACTS=./test-results/test-results.xml
+            if [ ! -f "$TEST_ARTIFACTS" ]; then
+              echo "Test artifacts are missing!"
+              exit 1
+            fi
+      - store_test_results:
+          path: test-results
   release:
     <<: *defaults
     steps:
